"""Add generation_job_id to GeneratedImage

Revision ID: 0e21ae426867
Revises: d6ee13127907
Create Date: 2024-11-05 17:36:55.095257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e21ae426867'
down_revision = 'd6ee13127907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'generation_jobs', ['generation_job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('generation_job_id')

    # ### end Alembic commands ###
