"""Added storage improvements and image relationships

Revision ID: 2e9780f838ce
Revises: 4c037250b423
Create Date: 2024-11-02 20:20:40.183991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e9780f838ce'
down_revision = '4c037250b423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_credit_transactions_created_at')
        batch_op.drop_index('idx_credit_transactions_type')
        batch_op.drop_index('idx_credit_transactions_user_id')
        batch_op.drop_constraint('credit_transactions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('model_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('prompt', sa.Text(), nullable=True))
        batch_op.create_index('idx_generated_images_model', ['model_id'], unique=False)
        batch_op.create_index('idx_generated_images_user', ['user_id'], unique=False)
        batch_op.drop_constraint('generated_images_job_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'trained_models', ['model_id'], ['id'])
        batch_op.drop_column('job_id')

    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=True))
        batch_op.create_index('idx_storage_locations_path', ['path'], unique=False)

    with op.batch_alter_table('trained_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weights_location_id', sa.Integer(), nullable=True))
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_constraint('trained_models_storage_location_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'storage_locations', ['weights_location_id'], ['id'])
        batch_op.drop_column('storage_location_id')

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('model_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('image_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('photobook_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('photobook_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('image_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('model_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('trained_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('trained_models_storage_location_id_fkey', 'storage_locations', ['storage_location_id'], ['id'])
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('weights_location_id')

    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.drop_index('idx_storage_locations_path')
        batch_op.drop_column('content_type')
        batch_op.drop_column('file_size')

    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('generated_images_job_id_fkey', 'generation_jobs', ['job_id'], ['id'])
        batch_op.drop_index('idx_generated_images_user')
        batch_op.drop_index('idx_generated_images_model')
        batch_op.drop_column('prompt')
        batch_op.drop_column('generation_params')
        batch_op.drop_column('model_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('credit_transactions_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_credit_transactions_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_credit_transactions_type', ['credit_type'], unique=False)
        batch_op.create_index('idx_credit_transactions_created_at', ['created_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
