"""Add checksum to StorageLocation

Revision ID: 3143159d8e6b
Revises: 43e8a47a5839
Create Date: 2024-11-06 00:48:37.064945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3143159d8e6b'
down_revision = '43e8a47a5839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checksum', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.drop_column('checksum')

    # ### end Alembic commands ###
